const fs = require('fs');

const path = 'src/App2.jsx';
let content = fs.readFileSync(path, 'utf8');

const replacements = [
  ['Tai khoan khong duoc phep dung', 'Tài khoản không được phép dùng'],
  ['Kiem tra ton kho', 'Kiểm tra tồn kho'],
  ['Chua kiem tra ton kho', 'Chưa kiểm tra tồn kho'],
  ['Da khop', 'Đã khớp'],
  ['Da doi chieu', 'Đã đối chiếu'],
  ['Chua doi chieu', 'Chưa đối chiếu'],
  ['Khong ro nguoi tao', 'Không rõ người tạo'],
  ['Quan ly tai khoan', 'Quản lý tài khoản'],
  ['Cap nhat POG', 'Cập nhật POG'],
  ['Dang xuat', 'Đăng xuất'],
  ['Dang nhap de cap nhat POG', 'Đăng nhập để cập nhật POG'],
  ['Tong quan van hanh', 'Tổng quan vận hành'],
  ['Tong quan check loss', 'Tổng quan check loss'],
  ['Tong quan check stock', 'Tổng quan check stock'],
  ['Kiem loss san pham', 'Kiểm loss sản phẩm'],
  ['Quet barcode, doi chieu stock va luu ky kiem', 'Quét barcode, đối chiếu stock và lưu kỳ kiểm'],
  ['Giao dien uu tien quet nhanh, nhap nhanh va xem lich su o cung mot man hinh.', 'Giao diện ưu tiên quét nhanh, nhập nhanh và xem lịch sử ở cùng một màn hình.'],
  ['Phieu quet hien tai', 'Phiếu quét hiện tại'],
  ['Nhap hoac quet barcode de them san pham, sau do dien stock he thong va stock thuc te.', 'Nhập hoặc quét barcode để thêm sản phẩm, sau đó điền stock hệ thống và stock thực tế.'],
  ['Ten ky kiem', 'Tên kỳ kiểm'],
  ['Nhap ma va nhan Enter', 'Nhập mã và nhấn Enter'],
  ['Lam moi phieu', 'Làm mới phiếu'],
  ['Xuat Excel phieu hien tai', 'Xuất Excel phiếu hiện tại'],
  ['Dang xuat...', 'Đang xuất...'],
  ['Luu ky loss', 'Lưu kỳ loss'],
  ['Dang luu...', 'Đang lưu...'],
  ['Dang o che do xem', 'Đang ở chế độ xem'],
  ['Dang nhap de luu ky loss dung chung.', 'Đăng nhập để lưu kỳ loss dùng chung.'],
  ['San pham chua co ten', 'Sản phẩm chưa có tên'],
  ['He thong', 'Hệ thống'],
  ['Thuc te', 'Thực tế'],
  ['Xoa khoi phieu', 'Xóa khỏi phiếu'],
  ['Phieu loss dang rong', 'Phiếu loss đang rỗng'],
  ['Bat dau quet barcode de tao danh sach.', 'Bắt đầu quét barcode để tạo danh sách.'],
  ['Lich su cac ky kiem loss', 'Lịch sử các kỳ kiểm loss'],
  ['Luu tru cac ky truoc do va xuat lai Excel bat cu luc nao.', 'Lưu trữ các kỳ trước đó và xuất lại Excel bất cứ lúc nào.'],
  ['Ky kiem loss', 'Kỳ kiểm loss'],
  ['Tong loss', 'Tổng loss'],
  ['Xuat Excel', 'Xuất Excel'],
  ['Chua co ky kiem loss nao duoc luu.', 'Chưa có kỳ kiểm loss nào được lưu.'],
  ['Check stock san pham', 'Check stock sản phẩm'],
  ['Danh sach san pham', 'Danh sách sản phẩm'],
  ['va loc theo barcode', 'và lọc theo barcode'],
  ['Quet barcode', 'Quét barcode'],
  ['Xoa loc', 'Xóa lọc'],
  ['Khong tim thay san pham phu hop.', 'Không tìm thấy sản phẩm phù hợp.'],
  ['Tim nhanh', 'Tìm nhanh'],
  ['Loc theo ten, SKU, barcode, line...', 'Lọc theo tên, SKU, barcode, line...'],
  ['chi anh huong khi khong co loc barcode', 'chỉ ảnh hưởng khi không có lọc barcode'],
  ['Tu khoa', 'Từ khóa'],
  ['VD: sku / ten san pham', 'VD: sku / tên sản phẩm'],
  ['Ban do line phu', 'Bản đồ line phụ'],
  ['Ban do line chinh', 'Bản đồ line chính'],
  ['Ban do line', 'Bản đồ line'],
  ['Chon nhom line, sau do cham vao mat ke A/B de xem chi tiet.', 'Chọn nhóm line, sau đó chạm vào mặt kệ A/B để xem chi tiết.'],
  ['Line chinh', 'Line chính'],
  ['Line phu', 'Line phụ'],
  ['Loi di chinh', 'Lối đi chính'],
  ['Thong bao he thong', 'Thông báo hệ thống'],
  ['Tao tai khoan moi', 'Tạo tài khoản mới'],
  ['Danh sach tai khoan', 'Danh sách tài khoản'],
  ['Bat/tat tai khoan va quyen theo tinh nang.', 'Bật/tắt tài khoản và quyền theo tính năng.'],
  ['Dang tai danh sach tai khoan...', 'Đang tải danh sách tài khoản...'],
  ['Chua co tai khoan nao.', 'Chưa có tài khoản nào.'],
  ['Khong luu duoc du lieu dung chung.', 'Không lưu được dữ liệu dùng chung.'],
  ['Khong luu duoc thong tin ton kho.', 'Không lưu được thông tin tồn kho.'],
  ['Tai khoan', 'Tài khoản'],
  ['Quet', 'Quét'],
  ['Loc', 'Lọc'],
  ['Them', 'Thêm'],
  ['Quan ly', 'Quản lý'],
  ['Chon module', 'Chọn module'],
  ['Tong quan', 'Tổng quan'],
  ['Lech', 'Lệch'],
  ['Dang nhap', 'Đăng nhập']
];

for (const [search, replace] of replacements) {
  // Use plain split/join to escape any regex characters and only match exact strings
  content = content.split(search).join(replace);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Script completed safely.');
